// Generated by gencpp from file dianracing_ros_huding/AddTwoInts.msg
// DO NOT EDIT!


#ifndef DIANRACING_ROS_HUDING_MESSAGE_ADDTWOINTS_H
#define DIANRACING_ROS_HUDING_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <dianracing_ros_huding/AddTwoIntsRequest.h>
#include <dianracing_ros_huding/AddTwoIntsResponse.h>


namespace dianracing_ros_huding
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace dianracing_ros_huding


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dianracing_ros_huding::AddTwoInts > {
  static const char* value()
  {
    return "c9caccfcada3b6a45d8528a23bccaf1a";
  }

  static const char* value(const ::dianracing_ros_huding::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::dianracing_ros_huding::AddTwoInts > {
  static const char* value()
  {
    return "dianracing_ros_huding/AddTwoInts";
  }

  static const char* value(const ::dianracing_ros_huding::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::dianracing_ros_huding::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::dianracing_ros_huding::AddTwoInts > 
template<>
struct MD5Sum< ::dianracing_ros_huding::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dianracing_ros_huding::AddTwoInts >::value();
  }
  static const char* value(const ::dianracing_ros_huding::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dianracing_ros_huding::AddTwoIntsRequest> should match 
// service_traits::DataType< ::dianracing_ros_huding::AddTwoInts > 
template<>
struct DataType< ::dianracing_ros_huding::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::dianracing_ros_huding::AddTwoInts >::value();
  }
  static const char* value(const ::dianracing_ros_huding::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dianracing_ros_huding::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::dianracing_ros_huding::AddTwoInts > 
template<>
struct MD5Sum< ::dianracing_ros_huding::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dianracing_ros_huding::AddTwoInts >::value();
  }
  static const char* value(const ::dianracing_ros_huding::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dianracing_ros_huding::AddTwoIntsResponse> should match 
// service_traits::DataType< ::dianracing_ros_huding::AddTwoInts > 
template<>
struct DataType< ::dianracing_ros_huding::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::dianracing_ros_huding::AddTwoInts >::value();
  }
  static const char* value(const ::dianracing_ros_huding::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DIANRACING_ROS_HUDING_MESSAGE_ADDTWOINTS_H
